-- Comments
CREATE TABLE comments(
rid INTEGER NOT NULL UNIQUE,
uid INTEGER NOT NULL UNIQUE,
descr VARCHAR(255) NOT NULL,
cid INTEGER NOT NULL,
    FOREIGN KEY(uid) REFERENCES signuplogin(uid) ON UPDATE CASCADE ON DELETE CASCADE 
);