-- FOLLOW
CREATE TABLE Follow(
sid INTEGER NOT NULL UNIQUE,
rid INTEGER NOT NULL UNIQUE,
uid INTEGER NOT NULL UNIQUE,
ispending Boolean,

    FOREIGN KEY(uid) REFERENCES signuplogin(uid) ON UPDATE CASCADE ON DELETE CASCADE 
);