-- CRUD
CREATE TABLE reelcrud(
rid INTEGER NOT NULL UNIQUE,
uid INTEGER NOT NULL UNIQUE,
videolink VARCHAR(255) NOT NULL,
songlink VARCHAR(255) NOT NULL,
caption VARCHAR(255) NOT NULL,
    FOREIGN KEY(uid) REFERENCES signuplogin(uid) ON UPDATE CASCADE ON DELETE CASCADE 
);
