-- SignUp and LOGIN
CREATE TABLE signuplogin(
uid INTEGER NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,


DOB DATE NOT NULL,
username VARCHAR(255) NOT NULL,

    PRIMARY KEY(uid);

);